export enum APP_SETTINGS {
  ARTICLE_PORT = 'ARTICLE_PORT',
  ARTICLE_DB_HOST = 'ARTICLE_DB_HOST',
  ARTICLE_DB_PORT = 'ARTICLE_DB_PORT',
  ARTICLE_DB_NAME = 'ARTICLE_DB_NAME',
  ARTICLE_DB_PASSWORD = 'ARTICLE_DB_PASSWORD',
  ARTICLE_DB_USER = 'ARTICLE_DB_USER',
  ARTICLE_JWT_SECRET = 'ARTICLE_JWT_SECRET',
  ARTICLE_REDIS_HOST = 'ARTICLE_REDIS_HOST',
  ARTICLE_REDIS_PORT = 'ARTICLE_REDIS_PORT',
  ARTICLE_REDIS_PASSWORD = 'ARTICLE_REDIS_PASSWORD',
  ARTICLE_REDIS_NAME = 'ARTICLE_REDIS_NAME',
  ARTICLE_REDIS_USER = 'ARTICLE_REDIS_USER',
}
